// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0LSBvQc00WuNayNgDlqWXwlW50ikcF0',
    appId: '1:593491112080:android:f59f7dd9456db7bc64e815',
    messagingSenderId: '593491112080',
    projectId: 'wealth-accrue',
    storageBucket: 'wealth-accrue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG0ih08yQ5RxOZ5rfZ7TwHiuES3LX7ltg',
    appId: '1:593491112080:ios:589fb4954f92c45964e815',
    messagingSenderId: '593491112080',
    projectId: 'wealth-accrue',
    storageBucket: 'wealth-accrue.appspot.com',
    androidClientId: '593491112080-lc3jcta0f75e09120nuf4jb5ec7hti5v.apps.googleusercontent.com',
    iosClientId: '593491112080-dcdj76c14obrsfso572of5d2tne3rjha.apps.googleusercontent.com',
    iosBundleId: 'in.wealthaccrue.wealthaccrue',
  );
}
